cassandra:
  contactPoints:
    - 127.0.0.1
  port: 9042
  localDataCenter: datacenter1
  keyspace: user_management

logging:
  level: INFO

elasticsearch:
  host: http://localhost:9200
  port: 9200
  index: user_management
