version: '3.8'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:4.1
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_START_RPC=true
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - '6379:6379'
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8
    ports:
      - '2181:2181'
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  api:
    container_name: nest_api
    build: .
    depends_on:
      - cassandra
      - redis
      - kafka
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - KAFKA_BROKER=kafka:9092
    command: npm run start:dev

volumes:
  cassandra_data: null
  elasticsearch_data: null
